[package]
name = "ss58-org"
version = "0.1.3"
edition = "2021"

[dependencies]
base58 = "0.2.0"
blake2 = "0.10.6"
hex = "0.4.3"
js-sys = "0.3.60"
yew = "0.20.0"

[dependencies.web-sys]
version = "0.3.60"
features = ["Clipboard", "Document", "HtmlInputElement", "HtmlSelectElement", "Navigator", "Window"]
