[package]
name = "ss58-org"
version = "0.2.0"
edition = "2021"

[dependencies]
base58 = "0.2.0"
blake2 = "0.10.6"
hex = "0.4.3"
js-sys = "0.3.64"
leptos = { version = "0.4.3", features = ["csr", "nightly"] }

[dependencies.web-sys]
version = "0.3.64"
features = [
    "Clipboard",
    "Document",
    "HtmlInputElement",
    "HtmlSelectElement",
    "Navigator",
    "Window",
]
