[package]
name = "ss58-org"
version = "0.1.4"
edition = "2021"

[dependencies]
base58 = "0.2.0"
blake2 = "0.10.6"
hex = "0.4.3"
js-sys = "0.3.61"
yew = { version = "0.20.0", features = ["csr"] }

[dependencies.web-sys]
version = "0.3.61"
features = [
    "Clipboard",
    "Document",
    "HtmlInputElement",
    "HtmlSelectElement",
    "Navigator",
    "Window",
]
