name: Build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  id-token: write
  pages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          target: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: latest

      - name: Install WASM Binary Toolkit
        run: sudo apt-get install -y binaryen

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: trunk build --release

      - name: Optimize WASM
        run: find dist -name "*.wasm" -exec wasm-opt {} -o {} -Oz -c --dae --dce --rse -s 4 --vacuum \;

      - name: Setup GitHub Pages
        # if: github.event_name == 'push'
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        # if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v2
        with:
            path: dist

      - name: Deploy to GitHub Pages
        # if: github.event_name == 'push'
        uses: actions/deploy-pages@v2
