name: PR
on:
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - name: Install trunk
        uses: jetli/trunk-action@v0.1.0
        with:
          version: latest

      - name: Install WASM Binary Toolkit
        run: sudo apt-get install -y binaryen

      - name: Build
        run: trunk build --release --public-url=/pr-${{ github.event.number }}/

      - name: Optimize WASM
        run: find dist -name "*.wasm" -exec wasm-opt {} -o {} -Oz -c --dae --dce --rse -s 4 --vacuum \;

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          destination_dir: pr-${{ github.event.number }}
